services:
  - type: web
    name: telegram-autogpt-safe
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements-safe.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.12
    healthCheckPath: /health
